### ISSUE TITLE
请停止滥用 GitHub 并都用自己的脑子来想问题

### ISSUE THREAD

**Issue by wbsdty331** [greatfire/wiki#102]
已举报，美分别和我bb

**Comment by liu149339750** [comment]
美分与5毛的撕逼大戏。

**Comment by wbsdty331** [comment]
我求求那些一口一个 共匪的
请不要再继续用自己的脚后跟想问题了好吗？

**Comment by LaoDaGe** [comment]
滚你的小确幸！ 

https://github.com/LaoDaGe/HellSlave

**Comment by honve** [comment]
狗日的，这里还有五毛？脑子坏了还能写代码？

**Comment by lushilei** [comment]
狗日的，这里还有五毛？脑子坏了还能写代码？

**Comment by Low-power** [comment]
If it isn't source, it isn't software.
Stop abusing GitHub!

**Comment by Leliana** [comment]
This is so stupid. Do you know how many people host their blogs on github? Have you ever used GitHub.io? 

If you think this is abuse, go and report all blogs.

So stupid. Nobody cares if you are blocked or not. We have the freedom to post anything we like.

**Comment by wbsdty331** [comment]
I reported this repo,Thanks. 在2016年05月07日 02:44 ，Leliana写道： This is so stupid. Do you know how many people host their blogs on github? Have you ever used GitHub.io? If you think this is abuse, go and report all blogs. So stupid. Nobody cares if you are blocked or not. We have the freedom to post anything we like. — You are receiving this because you commented. Reply to this email directly or view it on GitHub

**Comment by CPCer** [comment]
请停止滥用汉字！汉字是表达思想自由用的，不是用来给赵家人舔菊的呵呵

**Comment by wbsdty331** [comment]
@Andrews 汉字给你家美国主子舔菊

**Comment by percyalpha** [comment]
欢迎访问蓝灯论坛讨论 https://github.com/getlantern/forum

**Comment by Leliana** [comment]
You can "report" as you wish, and nothing will happen.

**Comment by luckypoem** [comment]
@wbsdty331 ，你这自干五，舔共匪的屁眼，舔上瘾了吧。继续舔，没人拦着你。共匪的大粪很香甜的，你多吃点

**Comment by xxxsen** [comment]
围观撕逼，真是闲得蛋疼。

**Comment by lyd87880938** [comment]
这年头五毛都进军github了。你妈死了。

**Comment by wbsdty331** [comment]
@lyd87880938

**你开心就好**

**Comment by honve** [comment]
@luckypoem 五毛是没有被墙够，他们希望这里也不来。他们就是被强奸了，还说强奸得爽一类人。
