### ISSUE TITLE
這個 issue tracker 多了很多應該 close 掉的 issue

### ISSUE THREAD

**Issue by Vdragon** [greatfire/wiki#13]
不爭取何來自由？
先前還不是因為有爭取才訪問得到 GitHub？
請不要進行自我審查，謝謝！

@Vdragon 
附帶一題：被封掉的話就翻牆吧！別因為牆有一扇隨時會關上的小門就故意遺忘**你們被牆圍住的事實**

**Comment by KrasnayaPloshchad** [comment]
長期的思想控制、資訊控制的確能影響人的認知。最近看泡泡網上伊闕唐的文章分析這種一黨磚政通過控制資訊傳播奴役思想意識之手段與其影響力，文筆甚是犀利，對這問題之論證十分深刻，值得一看。

**Comment by TsarNicholasII** [comment]
> @Vdragon
> 从历史上得到教训，我们已经不会像（部份）人中华人民共和国想那样问题了
> 从历史上得到教训，我们会对伊拉克，利比亚的今天感到触目惊心
> 
> 请去担心那些接触不到谷歌/ Twitter / Facebook / g0v.tw / www.appledaily.com.tw ...的人，而不是只担心一个GitHub 
> 请去担心那些怀揣自由的良好愿景却被利用来破坏他方稳定的人，而不是只担心一个挂靠在Github上上的项目

Нет, нет, Ливия и Ирак сегодня очень свободны и демократичны, они могут просматривать любой веб-сайт.
