### ISSUE TITLE
召唤管理删Issues

### ISSUE THREAD

**Issue by liu149339750** [greatfire/wiki#140]
我github设置不是很了解，不知道能不能删除Issues。
经常收到这个项目的Issues邮件通知，内容全是些脑残言论，虽然我对中国执政党没啥好感，但是强行抹黑这种行为就更加恶心了，里面发的内容带有强烈的个人情绪色彩，有些更是在诋毁人的智商，实在受不了，像老虎咬人这种新闻都能被用来作为共产党的劣根性的证据，我实在无语了。
这些反政府的Issues给我的感官就是一群傻蛋在不停的发表傻逼言论抹黑赤党与其领导人。一次两次还好，不停的来就让人恼火了。

**Comment by lynnprosper** [comment]
管理就是他么自己呀
