### ISSUE TITLE
原帖已被删，请大家先转后看！！ 政府已经控制了GreatFire自由浏览和相关人员，使用自由浏览进行刑侦

### ISSUE THREAD

**Issue by guo392** [greatfire/wiki#198]

**Comment by dou4cc** [comment]
你可以拿以往版本的自由浏览做个对比吗？

**Comment by dou4cc** [comment]
今年七八月之交，@GreatfireChina 就发issue称要配合《网络安全法》，照你的说法，这种暗示一直持续到8月底。之间有一个月时间，是不是长了些？

**Comment by guo392** [comment]
原来自由浏览是没有这些权限的。百度上看到自由浏览的旧版http://www.shaoit.com/android-freebrowser.html 没有任何权限。

七八月的时候GreatFire应该还没有被控制。发表这些通告的原因是和发表通告表示下架纽约时报一样。因为GreatFire在被调查时感觉时日无多，赶快发布声明自保。没想到还是被国宝完全控制了。现在这些帖子都被国宝删除了。
