### ISSUE TITLE
请官方开放源代码！

### ISSUE THREAD

**Issue by zjszzw** [greatfire/wiki#211]
现在，只有官方开放源代码，可以证实“自由浏览”任然“自由”，或者真如传言所说，“自由浏览”已被控制，请开放源代码。

**Comment by WoodsCheney** [comment]
@zjszzw  这种宣传反共反中的，是一般人做的了的么，他肯定不会提供源码，一旦提供了，就能定位到谁在做汉奸走狗了。不过你可以反汇编一下，估计就能知道哪位宵小之徒在此鼓噪
