### ISSUE TITLE
请和我们一起，别隔岸放火

### ISSUE THREAD

**Issue by linlexing** [greatfire/wiki#22]
如是墙内的兄弟建的，支持。如是境外的朋友，请不要点把火然后说：不反抗就烧死。至少要和我们处一个战壕，才有资格做这种事情。
这好比你在监狱放风的地方洒传单，你没事，里面人连放风机会都失去。说反抗，别站着说话不腰疼

**Comment by KexyBiscuit** [comment]
Put ONLY code here. 放再多fq用代码都没人会反对，但是放几个镜像列表就有点竭泽而渔的意味了。请给普通开发者留活路。

**Comment by LaoDaGe** [comment]
这逻辑无法自洽啊。假如人家是国内的人，你意思这样就没话说；假如人家是美国公民，人家要干什么又不受你国法律限制，你以什么理由阻止人家干这事呢？禁止干涉中国内政？

最后，希望 Github快点被封，到时我看你们找什么理由。已经被封了，人家就可以在上面随便怎样啦是不是？可惜Google Code现在停掉了

**Comment by alexgzhou** [comment]
@Vdragon 你们到底是要来争取战友的还是自己爽完发泄完就了事的？你们如果只顾自己爽，骂完了事，那你们就没有给墙内的人带来任何利益，你就是墙内的人的敌人；你们如果是要来帮助墙内的人，那就拜托不要说什么我们的东西不是理所当然的屁话，网络是open的世界，我们能访问的免费资源，难道不是我们理所当然拥有的。要传播就好好传播，我也反感墙，昨天晚上submit半天代码都上不去，忙到晚上两点多，你当我喜欢你们两方的任何一方吗，有什么理由喜欢给你带来麻烦的人，不管出于什么目的！！！还有，墙内的人需要有能力的人的帮助，所以喜欢goagent之类的项目，至少能让我们正常工作下去，只有经济发展了，思想才会更开放，整天忙着搬砖的民工哪个关心民主法治，只要有口饭吃就好了，所以，请帮助我们继续开放，至少不要把仅有的技术翻墙给我们毁了，谢谢手下留情

**Comment by haquasaiku** [comment]
不要怂，无论如何不可能完全封锁的，当局需要我们工作，需要我们稳定
有人压迫你，你不能说是被压迫者的错，哪个程序能通过这样的逻辑？
技术上的墙还能推倒，自己心中的墙怎么推？
一如既往支持greatfire，所有人都在为墙付出时间/精力/自我阉割等等的代价，如果不能推倒墙，我们终要付出更大的代价

**Comment by LaoDaGe** [comment]
@alexgzhou  我就是来顾自己爽的，抱歉没有共识，你要自己爽，我也要自己爽。你为什么不用 http://Coding.io 呢？那是叫一个速度快啊。等经济发展了思想开放了你再用Github不行吗？凭什么要别人都跟你站一个战线呢？各顾各爽，我不骂你骂谁？你就是活该被关在墙内啊！让我忍着这口气来为你的利益着想，你当你是谁啊？你的大局值几钱跟我有什么关系？ 对不起，我用VPN都用了这么多年了，我可不管你上Github多么困难，你又没给我钱买VPN。


你妈的等到你自己利益受损了就开始说大家应该团结到一个阵线，凭什么你要用的东西就是东西要小声说话不要让它被墙，我要用的东西就不是东西被墙了你的影子在哪？滚！大家各走各的路，没错我就是喜欢搞破坏的。凭什么我要忍气吞声为了你的小确幸小生活着想？

活该！

**Comment by alexgzhou** [comment]
@LaoDaGe 不配做人，基本没有人的素质

**Comment by alexgzhou** [comment]
@LaoDaGe @Vdragon 小号是遮羞用的吗，现在人工智能这么发达，但还是一眼看出你是狗不是机器

**Comment by LaoDaGe** [comment]
@alexgzhou  别抢道德制高点啊，你不就是那会两条腿走路的猪嘛

**Comment by LaoDaGe** [comment]
你们这么热心，给下面这些项目都提Issues抗议去啊，TMD全是敏感词竟然Github还没被封，我当一次刘睿哲好了，我去将下面这些包含敏感词敏感信息的项目全举报了要不要：

https://github.com/search?q=%E5%A4%A9%E7%81%AD%E4%B8%AD%E5%85%B1&type=Code&utf8=%E2%9C%93


你们这些这么热心的思想警察，快去让这个项目作者删除这段文章，这个项目作者故意的吧，怎么里面包含这么多法轮大法的文章？
https://github.com/Yuanduo/Opinion-Mining/blob/31051ab183e2cd5c153cecb60ac5ebf43052c74b/OpinionMining/input1/test3/1n-%20-%20%E5%89%AF%E6%9C%AC%20(13)%20-%20%E5%89%AF%E6%9C%ACn-.txt

**Comment by LaoDaGe** [comment]
这个项目又是怎么回事？ 

https://github.com/neemo14-15/-------------/issues

**Comment by liu149339750** [comment]
我也回复一下，让你们都收到一封邮件！

**Comment by roleyzhang** [comment]
俺再来补充两句(山东口音)
在我王八大朝当个写程序的如果不会翻墙就别说自己是抹代码的。上次12360强票插件导致github被墙我就一直翻墙上github了，没有啥不方便，刁包子一上台就这么折腾，还有弱智跟着是非不分。这楼自从台湾同学来表了态就已经歪了，顺便说台湾有政府有军队有国号，人家凭啥就是你王八大朝不可分割的一部分？有本事就打过去嘛，口炮算啥呢？火车站地摊上的国防报纸都说了分分钟灭了美日，各位大粪码农义和团小将在github被墙后可以阅读一下，能瞬间高潮。github被墙的伤痛瞬间治愈了。

github在攻击下都没认怂，各位非主流就急急来撒娇给党妈洗地了、让我瞬间肃然起敬，可惜在github当太监确实不易啊。这边没有微薄小秘书，没人删帖，一切都靠智商，非主流们除了嗓门高，蛋扯得比较长。其余都是在表演喜剧呢，看得我好欢乐。github也不是没有申诉的地方，前面楼上的大哥给了那么多链接，非主流们别闲着啊，加油去把蛋扯到底，最好把你们的shitdammdamm的蛋也一起扯下来。

**Comment by tutugreen** [comment]
不要污染邮件列表，开点有用的issue。

**Comment by LaoDaGe** [comment]
@tutugreen   抱歉打扰，大家可以点右边的 "Unsubscribe" 取消这条相关的 Notifications
