### ISSUE TITLE
请停止使用github传播

### ISSUE THREAD

**Issue by taogogo** [greatfire/wiki#3]
你们能不能去一些其他网站搞啊，这样下去github也会被封，你考虑过码农的感受么？你
就不能用github。co么？
为了得到“为民主自由做贡献”的头衔和夸赞，你就看着github被封而不顾么？
请使用其他域名，既可以去领民主勋章，又可以赚流量，何乐而不为啊
再补充一下，可以用邮件订阅来分发可用的域名和ip，不要让github冒这个风险。

**Comment by tomgeniewang** [comment]
如你这样的程序员不如改行去做公务员吧～作为程序员，你最该想的事情不是这里会不会被封，而是去想怎样不会再有墙。不过你真的不适合，你去做公务员吧，我相信他们会很愿意雇佣你为墙服务的因为你丝毫不介意成为历史的罪人～如果你能够有后代，这个帖子将永远伴随你后代的存在而存在～而她们也将会因为有你这样的祖先而感到耻辱～这就是你的成就～谢谢～

**Comment by tutugreen** [comment]
GreateFire.org开的，聪明的人知道原因，理由，抱怨能找到主体，如果不是国人维护的服务，又为什么要维护Github在中国的访问，Github如果在中国不能访问，中国的程序员将与世界脱轨，当然，更多的会去fQ。

**Comment by ahjsrhj** [comment]
说不定哪一天github也如同其它网站一样突然消失不见.


来自 魅族 MX3

-------- 原始邮件 --------
发件人：YuanMing <notifications@github.com>
时间：周二 1月27日 08:43
收件人：greatfire/wiki <wiki@noreply.github.com>
主题：Re: [wiki] 请停止使用github传播 (#3)

**Comment by 599316527** [comment]
Block 了之後還是可以翻牆用的嘛
要是向「恐怖主義」低頭了，這世界還能變好嗎？

**Comment by cvbnt** [comment]
奴才总不过是寻人诉苦。只要这样，也只能这样。有一日，他遇到一个聪明人。
“先生！”他悲哀地说，眼泪联成一线，就从眼角上直流下来。“你知道的。我所过的简直不是人的生活。吃的是一天未必有一餐，这一餐又不过是高粱皮，连猪狗都不要吃的，尚且只有一小碗……”
“这实在令人同情。”聪明人也惨然说。
“可不是么！”他高兴了。“可是做工是昼夜无休息的：清早担水晚烧饭，上午跑街夜磨面，晴洗衣裳雨张伞，冬烧汽炉夏打扇。半夜要煨银耳，侍候主人耍钱；头钱从来没分，有时还挨皮鞭……。”
“唉唉……”聪明人叹息着，眼圈有些发红，似乎要下泪。
“先生！我这样是敷衍不下去的。我总得另外想法子。可是什么法子呢？……”
“我想，你总会好起来……”
“是么？但愿如此。可是我对先生诉了冤苦，又得你的同情和慰安，已经舒坦得不少了。可见天理没有灭绝……”
但是，不几日，他又不平起来了，仍然寻人去诉苦。
“先生！”他流着眼泪说，“你知道的。我住的简直比猪窠还不如。主人并不将我当人；他对他的叭儿狗还要好到几万倍……”
“混帐！”那人大叫起来，使他吃惊了。那人是一个傻子。
“先生，我住的只是一间破小屋，又湿，又阴，满是臭虫，睡下去就咬得真可以。秽气冲着鼻子，四面又没有一个窗……。”
“你不会要你的主人开一个窗的么？”
“这怎么行？……”
“那么，你带我去看去！”
傻子跟奴才到他屋外，动手就砸那泥墙。
“先生！你干什么？”他大惊地说。
“我给你打开一个窗洞来。”
“这不行！主人要骂的！”
“管他呢！”他仍然砸。
“人来呀！强盗在毁咱们的屋子了！快来呀！迟一点可要打出窟窿来了！……”他哭嚷着，在地上团团地打滚。
一群奴才都出来了，将傻子赶走。
听到了喊声，慢慢地最后出来的是主人。
“有强盗要来毁咱们的屋子，我首先叫喊起来，大家一同把他赶走了。”他恭敬而得胜地说。
“你不错。”主人这样夸奖他。
这一天就来了许多慰问的人，聪明人也在内。
“先生。这回因为我有功，主人夸奖了我了。你先前说我总会好起来，实在是有先见之明……。”他大有希望似的高兴地说。
“可不是么……”聪明人也代为高兴似的回答他。
一九二五年十二月二十六日

**Comment by LaoDaGe** [comment]
你们发现没， @taogogo  的资料显示他是百度的员工！ 这次Github被DDoS为什么选择百度的JS？百度跟GFW真是情同手足！

**Comment by taogogo** [comment]
@LaoDaGe @cvbnt @tomgeniewang 
1、民主马甲你们好，如果你的star不超过10个，或者不懂技术，请不要在这里起哄，你看我也没用马甲是吧~~~
2、我参与民主团体寻求宪政被抓的时候，也没见你们这些德先生除了在网上瞎BB之外有啥表示。我追求德先生，但是我对于在github上放置greatfire严重抗议。。。
3、对事不对人，明辨出真知。
4、github作为一个代码托管的网站，如果被墙，会影响很多做开源技术、知识共享和freelance的同学，希望你们有同理心。

**Comment by soulofc** [comment]
star不超过10个就不懂技术么？taogogo少在这里卖弄了，即使你当年参与了宪政被抓，也只能说明你现在背叛和嬗变了。
看看编程随想引用的评论：

每次发生什么网站被封，就会有一大群国人跑过去让别人删内容，仿佛接到了省政府新闻办的删帖令。
你们什么时候才能醒悟，作恶的是你们政府，而不是几篇文章几个项目。
而且你永远也抓不住政府的G点，你以为删掉这删掉那就没事了？想的美。

在 2015-04-12 19:12:57，"taogogo" <notifications@github.com> 写道：


@LaoDaGe@cvbnt@tomgeniewang
1、民主马甲你们好，如果你的star不超过10个，或者不懂技术，请不要在这里起哄，你看我也没用马甲是吧~~~
2、我参与民主团体寻求宪政被抓的时候，也没见你们这些德先生除了在网上瞎BB之外有啥表示。我追求德先生，但是我对于在github上放置greatfire严重抗议。。。
3、对事不对人，明辨出真知。
4、github作为一个代码托管的网站，如果被墙，会影响很多做开源技术、知识共享和freelance的同学，希望你们有同理心。

**Comment by tomgeniewang** [comment]
@taogougou 不懂技术关系很大吗？我看某些人连怎么做人都不懂了才老火…不会做人只会做狗是不是很可悲…鲁迅写文章没好意思把狗字写出来，用奴隶文雅点给代替了。不过做狗就算了，还要助纣为虐，这就是恶狗，是不是更可悲更可怕更可恶…因为没有恶奴隶一词我也不敢新造，只好把狗字写出来了。
还有，我什么时候说过支持民主这回事～你一开就给我扣个支持民主的帽子是啥居心…
我在这里郑重表态：taogougou你要支持民主的话，我是绝对不会支持你的…我可不想被你脱下水…
话说封了这里会不会影响防火墙工作人员对于某种特殊的防火墙的研发啊？？你那么紧张干啥？

在 2015-04-12 19:12:57，"taogogo" <notifications@github.com> 写道：


@LaoDaGe@cvbnt@tomgeniewang
1、民主马甲你们好，如果你的star不超过10个，或者不懂技术，请不要在这里起哄，你看我也没用马甲是吧~~~
2、我参与民主团体寻求宪政被抓的时候，也没见你们这些德先生除了在网上瞎BB之外有啥表示。我追求德先生，但是我对于在github上放置greatfire严重抗议。。。
3、对事不对人，明辨出真知。
4、github作为一个代码托管的网站，如果被墙，会影响很多做开源技术、知识共享和freelance的同学，希望你们有同理心。

**Comment by guaitai** [comment]
这逻辑给跪了，当时没有greatfire的时候也没见您主子闲着，当别人文艺复兴的时候我们在搞文字狱，当大航海时代开启时我们在闭关锁国，当大数据时代来临时我们就有了GFW。我们不静下心来想一想为什么每次主子们总是走到世界对立面，却在这痛诉别人强奸时不配合

**Comment by taogogo** [comment]
@soulofc 因为用马甲只会让你表现出人性中恶的一面，失去了讨论的价值；
@tomgeniewang 你看你“咬”我，还臆测我会从中捞什么好处，你内心是多么丑陋；
@guaitai 兄台，我也在反抗GFW的蹂躏啊……我只是代表个人抗议这个项目放置在github上；

**Comment by tomgeniewang** [comment]
@taogogo 的确是啊，我的内心远远不及你的伟光正啊～～～哈哈哈

**Comment by ujfj1986** [comment]
这个不是github的问题，不能因为在github有这个项目，就ddos攻击github，如果这样，那么是不是就可以推论，因为手机、电脑可以上网看这些东西，以后国内就不要用手机和电脑？不要用网络？因为国内有信访部，所以就不要有政府？

**Comment by LaoDaGe** [comment]
@taogogo 
1、如果你一年的Public contributions都不超过3个，请不要在这里起哄，Github是为OpenSource服务的，你贡献只有3个，好意思出来说话么？
2、你参与什么民主团体寻求宪政被抓了关我什么事？是不是你是老大了已经？你有最高发言权了？就你懂斗争？你争取到最后挣个屁出来了？GFW透明了？屁都没挣出来，你有什么脸装成长者来教育别人学会妥协忍耐，你是宋江吧？我看你在百度，算是招安了。
3、对人不对事，就你有真知

最后，你有什么资格让别人为你考虑？你有为别人考虑过吗？人家没有违反Github的条约，人家有用的权利，你不爽你自己可以滚，凭什么让人家为了让你爽就得滚出Github？你是老太爷？还什么“祈祷并坐等河蟹大怪”，这脑残SM的程度，你真是心里恨不得GFW来强奸你让你爽吧？什么“兄台，我也在反抗GFW的蹂躏啊”，谁要跟你这种人站一个队伍？

我问你 @taogogo ，我的网站被大炮 DDoS了，你来关心不？你来为我的权益呐喊？还是你让我忍忍理性诉求？凭什么你要访问的网站被封了就不准我来用？滚吧！谁都是自私自利的，你跟我秀什么高尚？说得好像很有道理，骨子里其实就是：**你是少数人，你是下等人，你要为我们的大局服务！**

这种“精英大局观念”还真是受人欢迎，怪不得郜艳敏也能成最美感动女教师，谁反抗谁就是破坏我们山村美满的家庭，谁反抗谁就是在破坏我们中产阶级码农的小确幸，为了你们的小确幸，我们都得学会理性平各忍气吞声是吧？滚！你的利益是你的利益，我的权益是我的权益，上街游行示威也影响商店营业，我不是圣人，麻烦下次我上街抗议了，你就不要再躲在屏幕后面说我影响了街边商店营业没有考虑过店家的感受了，我不是圣人！

**Comment by taogogo** [comment]
@LaoDaGe 
虽然你出口成脏，但我捍卫你辱骂我的权利。
希望GFW早日坍塌，此无营养的项目能够从github消失，此项目的owner不再通过胁迫他人而获得荣誉和献金。
