### ISSUE TITLE
Firefox访问Google镜像结果链接出现Site offline

### ISSUE THREAD

**Issue by BarclayII** [greatfire/wiki#34]
近日访问Google镜像，点击搜索结果后出现Site offline - redirecting页面，随后被重定向至greatfire主页。

请问是什么问题？

**Comment by 101zjd** [comment]
GFW大幅度升级了有关技术，独裁国家对此乐此不疲！唯有此，才能保证其国民资源耗光、财产转移之前稳定局面。
