### ISSUE TITLE
使用 BBC 站内搜索出来一片空白

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [greatfire/wiki#39]
我用 BBC 的站内搜索查到却是一片空白，这是怎么回事？

**Comment by KrasnayaPloshchad** [comment]
在 BBC 页面的右上角有个白色的搜索框，从原站点打开页面输入文字能看到搜索结果，从镜像站输入文字得来的是一片空白，怎么办？

**Comment by 101zjd** [comment]
GFW由先前的防御变成主动进攻了，不要低估了独裁者和其技术之能力。
