### ISSUE TITLE
请给出需要利用github来传播的理由？

### ISSUE THREAD

**Issue by sn00011** [greatfire/wiki#4]
你们这样仗着GOV不敢封github吗？
你们干嘛不去找个随便什么博客来传播，因为github更安全，github很坚强是吗？

Github是个写代码的地方，用来搞什么自由，抗争，呵呵。。。

**Comment by langxuelang** [comment]
换个地方吧

**Comment by soulofc** [comment]
换地方？昨天让谷歌接受阉割，谷歌只好退出，用不不了谷歌的时候你们这些技术婊去要谷歌接受审查啊？现在又想迫使GITHUB接受阉割。技术婊，跟圣母婊一样操蛋。

**Comment by langxuelang** [comment]
@soulofc 请注意你的用语，真是为你感到羞愧。开口闭口脏话。

**Comment by stardiviner** [comment]
@langxuelang  不能接受别人说脏话，就是无法理解世界上别人为什么愤怒。难道也敢让一个老太太不要对你讲脏话？且不说人家还不是对你说的。用所谓的礼貌去压抑他人的情绪，就和封建礼教压抑人性一个本质。仗着自己的文明地位高级么？

**Comment by jerryling315** [comment]
@stardiviner 这是一个交流态度的问题，开口闭口脏话就算不是对着你说的，也说明了对面的这个谈话对象现在处在不冷静和不理性的状态；does it help?

**Comment by stardiviner** [comment]
@jerryling315 你不能强制别人文明，文明是个人意愿的遵守。如果强制要求别人怎么样？和强盗有什么区别？你不喜欢，你要文明的态度，可以，那是你的事。别人要不要是别人的事。难道我不扔垃圾在路上，还能强制要求别人也这么做？

**Comment by liu149339750** [comment]
蛋疼，对这种有争议的帖子，无视不就得了，一个回复都不给多好呀。不管楼主怎么抗议就当没看到就行了，回复个蛋呀。

**Comment by jerryling315** [comment]
@stardiviner 你这么说,没错; 但又说回来,什么叫强制?如此说来, 你为什么又要强制我不能去强制别人? 说到底, 无论说什么都是可以的, 我只是觉得文明交流无论从效率还是礼节上都比较好; 既然你觉得脏话是可以的, 那么久这样吧

**Comment by anyueruhui** [comment]
政治就像空气，可笑的是有些人还以为可以独善其身。

**Comment by soulofc** [comment]
凡是支持CCP的程序员混得都很差的，不明事理的人不论在什么领域都是亦步亦趋，浑浑噩噩

在 2016-05-13 09:15:42，"anyueruhui" <notifications@github.com> 写道：


政治就像空气，可笑的是有些人还以为可以独善其身。

**Comment by percyalpha** [comment]
可以用蓝灯科学上网 https://github.com/getlantern/mirror 下载

**Comment by wliu1215** [comment]
@MrBoog 你看不出那是因为你跟楼主一样的奴性和幼稚

**Comment by chn-yang** [comment]
我草 ,好多觉醒青年, 我的妈呀, 都是日本人的种吗

**Comment by iPandoraemon** [comment]
在技术平台上搞政治，某些人还觉得正常，还搬出网站的协议来说事。不要将政治和技术混在一起，搞政治的滚出GitHub是非常有必要的！
