### ISSUE TITLE
GITHUB是一个技术协作平台，非相关内容请移除

### ISSUE THREAD

**Issue by alex-chan** [greatfire/wiki#42]
GITHUB是一个技术协作平台，非相关内容请移除

**Comment by whq731** [comment]
月经再现 可以关了

**Comment by nailuoGG** [comment]
能放什么是由github官方决定的



—
通过 Mailbox 发送

**Comment by FuckTheGFW** [comment]
你规定的“相关”？你是“相关”部门养的狗？

**Comment by percyalpha** [comment]
Github使用协议没有规定不能放置非code的内容

**Comment by abcfy2** [comment]
奥巴马已经把总统法令迁移到github了，你怎么不去提issue，让美国总统把“不相关”的内容移出？

**Comment by zjhxmjl** [comment]
@alex-chan，放什么内容是其自由，至于担心会被封，如果你生在天朝，你就得有这个思想准备，回去仔细研究你的社会主义价值观吧！

**Comment by soulofc** [comment]
有人已经自觉去当有关部门的狗了。

**Comment by ItinerantSavage** [comment]
slave做惯了 会自觉维护master嘛 哈哈

**Comment by KrasnayaPloshchad** [comment]
这都是☭教育出来的

**Comment by liu149339750** [comment]
好好做人！

**Comment by jonzrj** [comment]
还是林语堂说的好，虽然那句话不是他说的

**Comment by serious198706** [comment]
这是跪久了不知道怎么站了是吧。

**Comment by roleyzhang** [comment]
从小脖子围着红尿布，脑子被洗傻了才跑墙外来冒充支书。这智商还知道github，不容易啊

**Comment by swituo** [comment]
听一楼的~ 放点各种语言的“FUCK GFW！”上去，满足他一下！
Console.WriteLine("Fuck GFW!");

**Comment by SolskGaer** [comment]
共党的狗吧

**Comment by KrasnayaPloshchad** [comment]
至少是个☭和政府教育出来的螺丝钉







发件人: SolskGaer
发送时间: ‎2015‎年‎3‎月‎31‎日, ‎星期二 ‎14‎:‎40
收件人: greatfire/wiki
抄送: Krasnaya Ploshchad





共党的狗吧
