### ISSUE TITLE
chinadigitaltime can not slide from left to right

### ISSUE THREAD

**Issue by Mybestway** [greatfire/wiki#44]
Chinadigitaltime can not slide from left to right and zoom out. Browser: chrome. System:android

**Comment by Mybestway** [comment]
I've found the solution to it myself.
真想骂人。本来是把这个网页介绍给不会翻墙的人。谁知出来个残废的网页，不能缩放不能滑动。别人就一点兴趣没了。
一段时间前数字时代用dt3网址时还没问题。现在改版了改成这样，要跳转还在顶部加了几个字，结果是网页看不全了。在手机试了很多浏览器，只有火狐能正常浏览。
把浏览器脚本禁用后跳转网址出来了，就是https://cdt.global.ssl.fastly.net/?rwb3498472=1 。把后面的?rwb3498472=1 加到其他镜像网址后面就可以打开可以缩放的网页，如博讯的https://boxun22.global.ssl.fastly.net/?rwb3498472=1
Anyway, thanks to the group of greatfire

**Comment by greatfire-martin** [comment]
@Mybestway 谢谢你的反馈。我觉得这个CDT的问题现在解决了。情再尝试。CDT 也有一个安卓免翻墙应用。在 https://github.com/greatfire/wiki 可以下载。

**Comment by Mybestway** [comment]
@greatfire-martin 谢谢！在安卓版chrome问题解决，opera也没问题了。但安卓自带浏览器还是不能滑动。在塞班的opera上也不能。有时还会跳转到https://bitbucket.org/greatfire/wiki。
建议把网页上面那几行字取消，放到https://github.com/greatfire/wik，最大限度增加镜像网页兼容性。那几行字还影响到一些浏览器如UC对网页的重新排版，搞得网页很乱。
