### ISSUE TITLE
你们滚出技术圈好么

### ISSUE THREAD

**Issue by bk201sama** [greatfire/wiki#45]
老子github访问都那么困难，自己开服务器去讨论政治好么，真他妈的烦，哪里可以举报

**Comment by ahjsrhj** [comment]
一般要刷新两三次才能打开…


来自 魅族 MX3

-------- 原始邮件 --------
发件人：bk201sama <notifications@github.com>
时间：周一 3月2日 13:55
收件人：greatfire/wiki <wiki@noreply.github.com>
主题：[wiki] 你们滚出技术圈好么 (#45)

**Comment by whq731** [comment]
月经ISSUE 关了吧

**Comment by bk201sama** [comment]
我只是来骂一句，很恼火，半天刷开，真当程序员不发火。已经邮件联系github看官方怎么办了

**Comment by KrasnayaPloshchad** [comment]
自己找个洋 DNS 地址用用就好办了

**Comment by abcfy2** [comment]
github: 怪我咯？

**Comment by ahjsrhj** [comment]
😂


来自 魅族 MX3

-------- 原始邮件 --------
发件人：Feng Yu <notifications@github.com>
时间：周一 3月2日 20:13
收件人：greatfire/wiki <wiki@noreply.github.com>
抄送：rhj <aha199277@qq.com>
主题：Re: [wiki] 你们滚出技术圈好么 (#45)

**Comment by Epsin** [comment]
話說半天才刷開，那只能是個人水平問題

**Comment by udbmnm** [comment]
不翻墙也是秒开

**Comment by ahjsrhj** [comment]
关键一好好的网站马上到了需要翻墙才能进不心塞么！


来自 魅族 MX3

-------- 原始邮件 --------
发件人："@Life" <notifications@github.com>
时间：周二 3月3日 14:43
收件人：greatfire/wiki <wiki@noreply.github.com>
抄送：rhj <aha199277@qq.com>
主题：Re: [wiki] 你们滚出技术圈好么 (#45)

**Comment by roleyzhang** [comment]
有些人脑子就是水多，网站被墙就怪发言的人，不去想想修墙的才是罪魁，你支真是奇葩多                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: rhjSent: Tuesday, March 3, 2015 17:46To: greatfire/wikiReply To: greatfire/wikiSubject: Re: [wiki] 你们滚出技术圈好么 (#45)关键一好好的网站马上到了需要翻墙才能进不心塞么！


来自 魅族 MX3

-------- 原始邮件 --------
发件人："@Life" <notifications@github.com>
时间：周二 3月3日 14:43
收件人：greatfire/wiki <wiki@noreply.github.com>
抄送：rhj <aha199277@qq.com>
主题：Re: [wiki] 你们滚出技术圈好么 (#45)

>不翻墙也是秒开
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/greatfire/wiki/issues/45#issuecomment-76895193

—Reply to this email directly or view it on GitHub.

**Comment by coffeesherk** [comment]
跪着的永远不会想着去站起来，而是怎么跪的舒服

**Comment by percyalpha** [comment]
用蓝灯访问Github会快很多 https://github.com/getlantern/forum#蓝灯lantern最新版本下载
