### ISSUE TITLE
请停止滥用 GitHub

### ISSUE THREAD

**Issue by KexyBiscuit** [greatfire/wiki#46]
GitHub 不是存储此类信息的网站。

**Comment by KrasnayaPloshchad** [comment]
侬以为自己是谁？

**Comment by roleyzhang** [comment]
被墙惯了、以为github还有党支部啊？发布什么还要批准？

**Comment by whq731** [comment]
请指出违反了github的哪条使用条款，不可以提供“具有政治争议的信息内容的网站链接”？

**Comment by percyalpha** [comment]
See #42

**Comment by udbmnm** [comment]
其实一开始我是拒绝的。。。

**Comment by KrasnayaPloshchad** [comment]
☭的思想道德建设还是很得力滴





发件人: roleyzhang
发送时间: ‎2015‎年‎3‎月‎10‎日, ‎星期二 ‎12‎:‎19
收件人: greatfire/wiki
抄送: Krasnaya Ploshchad





被墙惯了、以为github还有党支部啊？发布什么还要批准？

**Comment by lzz5235** [comment]
GitHub is a kind of code website to share and communicate our mind,not politic website!
You can develop some tools to fight with GFW, not just make this website into navigation site.
I had to say this behavior is so low!

**Comment by percyalpha** [comment]
@lzz5235 Please kindly go to this repo "A ticket for every new law of the United States, as of March 12, 2014." https://github.com/sunlightlabs/us-laws

**Comment by linchuche** [comment]
leave a comment
