### ISSUE TITLE
自由浏览器是开源的吗？

### ISSUE THREAD

**Issue by skepts** [greatfire/wiki#48]
小白一个，不太懂… 
不好意思怀疑你们，，如果开源不利，那还是别开源了……

**Comment by percyalpha** [comment]
我们希望能开源。但是开源可能会方便了GFW。所以现在还在讨论中。

**Comment by linux-86** [comment]
不要开源  出个桌面版浏览器 谢谢

**Comment by 101zjd** [comment]
必须保证开源不让独裁者所利用的前提下去讨论。
