### ISSUE TITLE
自由浏览器经常弹出 ssl certificate error alert

### ISSUE THREAD

**Issue by cavi** [greatfire/wiki#51]
但是翻墙正常 这个提示很烦人  应该算是bug?

**Comment by LNDDYL** [comment]
你手機的系統時間不對吧？

**Comment by cavi** [comment]
系统时间是对的 应该不是时间的原因 不过最近几天又恢复正常了 无论如何还是感谢你的回复：）

**Comment by percyalpha** [comment]
cc @f998

**Comment by f998** [comment]
好  这个问题我再看看
以前我也遇到过几次  后来就没法再现
2015年3月28日 下午12:41于 "percyalpha" <notifications@github.com>写道：

**Comment by percyalpha** [comment]
解决了。如果还有问题，请重新打开这个issue
