### ISSUE TITLE
轮子已经攻占GitHub了？

### ISSUE THREAD

**Issue by Sigma-Algebra** [greatfire/wiki#52]
卧槽。。。这东西和开源项目有毛关系？和代码程序有啥关系？
我看到所有抗议的issue全被关了，这根本就和共产党的看谁不顺眼就屏蔽谁没啥区别，轮子哪来的脸去反的？

**Comment by tcdw** [comment]
什么鬼

**Comment by Sigma-Algebra** [comment]
偶然看到这个，除了一个readme和几个轮子网站其他啥都没有
