### ISSUE TITLE
你（你们）终于干了一件挖祖坟的事儿

### ISSUE THREAD

**Issue by jaywcjlove** [greatfire/wiki#53]
天堂被你搞沦陷了，只能入地狱了。

**Comment by tutugreen** [comment]
怪谁咯。

**Comment by Draveness** [comment]
你是 SB 么?傻逼

**Comment by jaywcjlove** [comment]
@Draveness sb 翻墙这种工具需要分享到这里么，下载工具网站大把的，分享的还是打包好的软件，要像clowwindy样， 分享点儿有料的，被人玩儿了还这里傻逼嘚瑟的。

**Comment by Draveness** [comment]
你特么就是一个傻逼, 你跪着挺舒服么, 你妈是不是炸了, 分享个jb 有料的, 就你也特么陪当程序员, 我真是干了你全家了? 还特么来骂别人怎样, 傻逼, 干你妈的 @jaywcjlov

**Comment by Draveness** [comment]
@jaywcjlove 哦, 你牛逼你牛逼, 是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是是

**Comment by Draveness** [comment]
@jaywcjlove 我觉得跟你这种人说啥都没用, 脑残就是脑残,  我真是想太多

**Comment by roleyzhang** [comment]
自干五别污染我的邮件列表，滚回墙内做奴才去，看greatfire不爽可以找github举报，别跑这里来表演负智商                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: kenny.wangSent: Sunday, April 5, 2015 03:42To: greatfire/wikiReply To: greatfire/wikiSubject: Re: [wiki] 你（你们）终于干了一件挖祖坟的事儿 (#53)@Draveness sb 翻墙这种工具需要分享到这里么，下载工具网站大把的，分享的还是打包好的软件，要像clowwindy样， 分享点儿有料的，被人玩儿了还这里傻逼嘚瑟的。

—Reply to this email directly or view it on GitHub.

**Comment by jaywcjlove** [comment]
@roleyzhang 在墙外做奴才做的理直气壮。...
