### ISSUE TITLE
请将非搜索页面移除！

### ISSUE THREAD

**Issue by lzz5235** [greatfire/wiki#58]
请将非搜索相关的新闻网站，社交网站页面移除，政治意味太浓了！

如果github持续被ddos，会不会存在反向屏蔽中国ip？如果这样，greatfire功不可没！

**Comment by tutugreen** [comment]
不管怎么说，他(们)达到都能目的。

**Comment by Harvesty** [comment]
怎么感觉有一个强盗抢劫某个人，这个人躲进了超市，结果超市被强盗砸了。
结果有人就说：“都怨这个 倒霉蛋，是他害的我们所有人都不能买东西！”

**Comment by Tianyugao** [comment]
最顶上这大哥逻辑也是醉了。

**Comment by lzz5235** [comment]
我宁可希望github屏蔽，也不希望github天天遭受ddos，如果这种ddos成为常态，导致的代码传不上去，你不知道这有多恶心么？！

**Comment by lzz5235** [comment]
我就是这个意思，这家超市是最大的，有我想要的一切。现在这家超市因为这种倒霉蛋，让我没法购买自己想要的东西，你说我恨不恨倒霉鬼！你别承认，这就是人性的弱点!

在 2015年3月28日 上午10:37，Harvesty <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>写道：

**Comment by lzz5235** [comment]
被ddos的直接原因就是出现了境外媒体和社交平台，反而搜索的信息不代表你能访问，所以危害不大!

Tianyugao <notifications@github.com>于2015年3月28日星期六写道：

**Comment by Harvesty** [comment]
突然感觉自己智商下降了不少，要警惕一下，往后这种讨论尽量少参与，说不定哪天智商变负数。

**Comment by AnthraX1** [comment]
脑残啊？新闻和社交网站什么时候成政治了？你国敏感就要全世界和它一起敏感？

**Comment by percyalpha** [comment]
见 #1
