### ISSUE TITLE
我个人出钱租VPS给你，请把这个项目搬出github

### ISSUE THREAD

**Issue by nomagick** [greatfire/wiki#6]
如题，现在DO的VPS那么便宜，你买不起我买个给你，求求你别在这玩火了

你要是喜欢github这种东西我在VPS搭个gitlab给你，求求你别在这玩火了

**Comment by fortissimoX** [comment]
@EpisodeXI 神预言。。linode也被封。。

**Comment by WangZhengmao** [comment]
你也配当赵家人？
他想封你还需要理由？greatfire撤走了就不封了？

**Comment by 02015678** [comment]
naive
你觉得你自己买的那个VPS能顶得住TB级的DDoS吗？
Github能顶得住，而且对greatfire项目并无怨言，也没有强制关停greatfire项目。

你若是希望更多的学习编程，就应当清楚的知道GFW对你的影响，绝不仅仅是Github的事情。
例如，你做iOS开发，却发现官方开发工具的下载链接太慢甚至无法打开，于是改为从国内镜像下载，所以会怎样呢？就是著名的Xcode Ghost事件了。

**Comment by shyandsy** [comment]
@avastms  
无意间路过看到，只想问一下为什么在github建这样的项目是玩火？读完楼上一众回复，我都没明白你的初衷，求详解。

**Comment by iwinux** [comment]
替楼主回答一下……「关你屁事」

**Comment by shyandsy** [comment]
你难道不觉得，这句话也适用于你自己？关你屁事，@你了？

发自我的 iPhone

**Comment by avastms** [comment]
@shyandsy GreatFire从来没有好好把Github当做一个软件仓库，一直都是当做下载站，宣传站。

对于能翻墙的人来说，Github封不封问题都不大，只要功夫网还是黑名单，一切无所谓。 但对于不能翻墙懒得翻墙的人来说，Github封和不封的区别就很大了。不幸的是后者是大多数，中国现在和未来真正有代表性的力量也是后者。

当时提这个Issue的时候GreatFire在Github只有这一个Repo，我也并不知道GreatFire是由U.S. GOV资助的，还以为是国内几个小愤青。

在了解到GreatFire本质是一些人在从美帝手里骗取民主经费之后，我也就没什么可说的了。

GreatFire从来没有主持开发过像样一点的项目，策反也不力，现在经费已经枯竭了吧，所以你看现在它也没啥活跃度了。

**Comment by shyandsy** [comment]
原来是这样，感谢答疑。


发自我的 iPad

**Comment by WeirdoShaw** [comment]
本来Github应该是一个交流代码的地方，在这里直接发商业广告，技术相关一概没有，issue里面全是政治敏感内容（对错不谈）很TM让人恶心。

**Comment by soulofc** [comment]
没人逼你看这个issue，你可以不关注这个issue啊，很怀疑阁下很是伪装成程序员的宣传员，你档那才叫恶心，还有那7个贪官之匪首。

在 2016-10-18 18:38:01，"WeirdoShaw" <notifications@github.com> 写道：


本来Github应该是一个交流代码的地方，在这里直接发商业广告，技术相关一概没有，issue里面全是政治敏感内容（对错不谈）很TM让人恶心。

**Comment by Hcreak** [comment]
傻逼玩意
