### ISSUE TITLE
翻墙过来给 GFW 洗地的都是怎么想的？

### ISSUE THREAD

**Issue by qifei** [greatfire/wiki#64]
GFW 基本是合法的。某些人说什么透明度不够，你他妈有什么权利要求透明度啊？
Twitter Facebook Google GitHub ... 都是违法境外网站，你们不应该自觉抵制吗？请滚远好么？

整天说只谈技术，拒绝政治的，脑子进水了么？你只是选择屈服强权政治而已，根本没有反抗的能力，而且连念头都丧失了。一切皆是政治，除非你与世隔绝。你他妈的来这里辱骂 GreatFire 就是在参与政治。

你们费劲巴拉露出脑袋就是为了说：这些围栏是为了保护我们，哪个国家都有围栏，只是透明度还需要健全。

**Comment by zhouyiji** [comment]
GFW怎么合法了，经过人代会审议了吗

**Comment by Scarittagle** [comment]
@qifei 不觉得你说的话在自相矛盾吗 我倒是觉得你在给GFW洗地

**Comment by roleyzhang** [comment]
楼主是想洗地还是想自相矛盾？GFW的存在连匪共都没有公开承认，合什么法？匪共的所谓法有具体可操作条款么？永远都是相关法律法规，至于是不是相关到匪共他麻痹里、也只有他麻痹的知道了。有些脑子进水的家伙总以github是个净土，自己他麻痹的是个阉货自居。还要冒傻泡什么你们有本事怎么不去干倒GFW云云。要知道独裁者不需要你出手，他知道你存在并且他无法消灭你就已经足够他寝食难安了。要不然匪共也不会耍流氓攻击github和派不少傻逼来搅浑水了。反抗在力量对比不平衡状态下，保存实力，关键时刻出手，这对匪共就是最大的威胁。不要妥协气馁，坚持做让匪共恶心和睡不着的事情就是革命。

**Comment by tutugreen** [comment]
看了LZ的话感觉十分搞笑。又或者是十分悲伤。

好吧默默地看了下LZ的Star列表。。。

还有，不管是哪方，不要带“匪”字，看着真像是##的。

**Comment by guilipan** [comment]
以前信息不对称加上党的疯狂宣传,人都被洗脑了,都丧失独立思考的能力了,现在有了互联网,80后90后们接触了更加多元化的世界,没那么容易被洗脑了,于是GFW出现了。。

**Comment by swituo** [comment]
我相信LZ的话，因为在我朝，DANG就是法！如果敢鞭笞DANG，那就让你女票女昌！

**Comment by udbmnm** [comment]
duang!!!!!!!!!!!!!!!GitHub 一直都可以duang，要翻？duang~~

**Comment by Misaka-11037** [comment]
好大的钩！我咬~

**Comment by liu149339750** [comment]
LZ脑残。其实我只是要让你们都收一封邮件的。

**Comment by Sigma-Algebra** [comment]
star列表那个笑死。。。为了翻墙才来上GitHub，难怪会对geek们厌恶政治内容那么来劲。。。人家就是键盘政治家你不让他谈政治他不杀了你啊

**Comment by wy193777** [comment]
前两行是引用吧@Scarittagle

**Comment by qifei** [comment]
某些人智商堪忧，语文老师死得早。

**Comment by Guhhhhaa** [comment]
不管如何讨论，我觉得应该明确一点，GFW本来是不应该存在的。这是一个前提吧。
