### ISSUE TITLE
GREATFIRE请滚出去！！你自己去反共不要带上别人！

### ISSUE THREAD

**Issue by fangzhouzi** [greatfire/wiki#65]
程序员网站讨论技术就讨论技术 不要讨论政治 ！！

**Comment by roleyzhang** [comment]
傻逼真多，谁带你了？别污染我邮件列表了，智商低滚回墙内用百度去好了，谁请你来了？                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: fangzhouziSent: Wednesday, April 1, 2015 12:40To: greatfire/wikiReply To: greatfire/wikiSubject: [wiki] GREATFIRE请滚出去！！你自己去反共不要带上别人！ (#65)程序员网站讨论技术就讨论技术 不要讨论政治 ！！

—Reply to this email directly or view it on GitHub.

**Comment by XL2014** [comment]
人家放什么关你你什么事儿? 不爽就去report abuse,别出来秀智商..
奴才真多,好好跪着吧...

**Comment by guaitai** [comment]
楼这群人什么逻辑，强奸案不去谴责强奸犯，却在这大骂受害者穿的少

**Comment by AnthraX1** [comment]
greatfire没有反共啊，只是反对网络审查。
再说，反共有错么？

**Comment by bbk0701** [comment]
@fangzhouzi 对于向您这类自我审查的货俺只能说："跪久了，自然站不起来了~"

**Comment by inapp123** [comment]
长大终会懂得。建议你去谷歌一下"8的平方"事件 请自己吧它算出来填入搜索框

**Comment by andres-lee** [comment]
要是github因为你而被墙，就fuck你了。

**Comment by LaoDaGe** [comment]
@fangzhouzi  你自已来丢人现眼也请不要带上“方舟子”的ID！

**Comment by guilipan** [comment]
明显是五毛刚申请的小号,看下注册时间就知道了,大家不用这么激动,这都是国内门户网站评论的一贯做法了

**Comment by percyalpha** [comment]
明显是五毛刚申请的小号,看下注册时间就知道了

**Comment by udbmnm** [comment]
```反毛线，反不反和你有毛线关系，别人干什么别骂行不？```

**Comment by Flyflyer** [comment]
只有说楼主傻逼了！

**Comment by jhy311** [comment]
我怎么觉得你该滚回墙内，嗯？！🖕

**Comment by JackieGmanLu** [comment]
滚回墙内的那群人你们等着，到时候连上个Github都要翻墙你看他们不骂死你
